export enum EnvEnum {
    DATABASE_URL = 'DATABASE_URL',

	IGDB_CLIENT_ID = 'IGDB_CLIENT_ID',
	IGDB_ACCESS_TOKEN = 'IGDB_ACCESS_TOKEN',

	JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
	JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
}