export enum EnvEnum {
    DATABASE_URL = 'DATABASE_URL',

	IGDB_CLIENT_ID = 'IGDB_CLIENT_ID',
	IGDB_ACCESS_TOKEN = 'IGDB_ACCESS_TOKEN',

	JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
	JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',

	SMTP_HOST = 'SMTP_HOST',
	SMTP_PORT = 'SMTP_PORT',
	SMTP_USER = 'SMTP_USER',
	SMTP_PASSWORD = 'SMTP_PASSWORD',
	RESEND_API_KEY = 'RESEND_API_KEY',

	EMAIL_FROM = 'EMAIL_FROM',
	FRONTEND_URL = 'FRONTEND_URL',
}